server:
  port: 8003

spring:
  application:
    name: admin
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/shortlink?useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&allowMultiQueries=true&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useSSL=false
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 2002

